general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "None"

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Always" }

[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
action = "ClearHistory"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[font]
size = 12.0

[font.normal]
family = "Monaspace Argon Var"
style = "Regular"

[font.bold]
family = "Monaspace Argon Var"
style = "Bold"

[font.italic]
family = "Monaspace Argon Var"
style = "Italic"
