
# General
set -g prefix C-Space

set -g default-terminal "tmux-256color"
set -g mouse on
set -g set-clipboard on

setw -g mode-keys vi

# Indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Keybinds

# Use | and - to split panes
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# Easy config reload (<prefix> r)
unbind r
bind r source-file ~/.tmux.conf\; display "Reloaded!"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'catppuccin/tmux#v2.1.3'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g @floax-change-path 'true'


# Status Bar
set -g status-position top

# Status Left
set -g status-left-length 100
set -g status-left ""

set -g window-status-format         " #I: #W#{?window_zoomed_flag, 󰍉,} "
set -g window-status-current-format " #I: #W#{?window_zoomed_flag, 󰍉,} "

set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_mauve;}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_lavender}"
set -g window-status-activity-style "bg=#{@thm_surface_0},fg=#{@thm_red},bold"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"

set -g window-status-current-style "bg=#{@thm_lavender},fg=#{@thm_bg},bold"

# Status Right
set -g status-right-length 100
set -g status-right ""

set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_blue}]  #{pane_current_path} | " #full-path
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_green}]  #S "


run '~/.tmux/plugins/tpm/tpm'

