set -g prefix C-Space

set -g mouse on
set -g set-clipboard external

setw -g mode-keys vi

# Terminal + color
set -g default-terminal "tmux-256color"
set -ga terminal-features ",*:RGB"

set -sg escape-time 0
set -g history-limit 50000
set -g focus-events on

# Indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Keybinds

# Use | and - to split panes
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Easy config reload (<prefix> r)
unbind r
bind r source-file ~/.tmux.conf\; display "Reloaded!"

# Plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'catppuccin/tmux#v2.1.3'

# Config catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

# Load catppuccin
run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

# status-left look and feel
set -g status-left ""
set -g status-left-length 100

# status-right look and feel
set -g status-right ""
set -g status-right-length 100

set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#{?client_prefix,#{#[bg=#{@thm_green},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"

# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "Window"

set -g window-status-format " #I#{?#{!=:#{window_name},Window}, #W,}#{?window_zoomed_flag, 󰁌,} "
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window}, #W,}#{?window_zoomed_flag, 󰁌,} "

set -g window-status-current-style "bg=#{@thm_lavender},fg=#{@thm_bg},bold"

#set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"

set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_pink}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_lavender}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"

# tmux bar
set -g status-position top
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "left"

# start tpm
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'

